### ISSUE TITLE
AppRole supports only approle path

### ISSUE THREAD

**Issue by bsbontchev** [abedra/libvault#115]
Issue: approle authenticator can be enabled under a path different than approle but AppRole supports only approle path
Environment: curl 7.61.1, libvault-0.52.0, Vault v1.8.2

approle enabled under "myapprole" path:
...
Vault::Sys::Auth authenticator(root_client);
Vault::Path path("myapprole");
Vault::Parameters parameters;
Vault::ValueVariant type("approle");
parameters.insert(std::make_pair("type", type));
auto response = authenticator.enable(path, parameters);

AppRole has "approle" path hardcoded.
...
Vault::Url Vault::AppRole::getUrl(const Path &path) const {
  return client_.getUrl("/v1/auth/approle/role/", path);
}

**Comment by abedra** [comment]
FIxed in https://github.com/abedra/libvault/commit/b8f435933f3498f0d5bd9698db9cf036af3d057b and released in https://github.com/abedra/libvault/releases/tag/0.54.0
