### ISSUE TITLE
Windows: libvault dll name shouldn't be `vault.dll` since `Vault.dll` is already a system lib on Windows

### ISSUE THREAD

**Issue by SpaceIm** [abedra/libvault#116]
dll name is `vault.dll` but `Vault.dll` is a system lib on Windows, so there is a conflict here where runtime loader will find system `Vault.dll` first (windows is case insensitive) instead of `vault.dll`.

**Comment by abedra** [comment]
I think the PR referenced above should do the trick, but I don't have a Windows build environment to verify. Can you confirm?

**Comment by abedra** [comment]
Released in 0.57.0
