### ISSUE TITLE
How should VaultClient.h be used?

### ISSUE THREAD

**Issue by k-kdan** [abedra/libvault#121]
In order to connect to the vault's server, I need to request an authorization url with the client certificate and the client key. From what I see in VaultClient.h, I first need to create a Vault client, but creating the client requires some kind of token, or username/password ...etc, which I don't have. All I have is the client certificate, and the client key. The mount path is at /oidc.

- I tried to create a Client using the TlsStrategy (which takes a certificate and key), but the mount path was set to "cert", which is not enabled.

- I tried to create a Client with the TokenStrategy with random letters as the token, so I can use that client to make a post request, that did not work either.

- I found an HttpClient class, which can make post requests without the need to create a client first, but there was no method that takes a certificate & key, as well as additional arguments

**Comment by abedra** [comment]
There are many examples of use in the example folder, and more can be found in the integration tests
