### ISSUE TITLE
lib-json as 3rd party

### ISSUE THREAD

**Issue by s1Sharp** [abedra/libvault#122]
libvault/lib/json.hpp - perhaps this file should be listed as a 3rd-party or external library as gitsubproject? it can be as a subproject for CMake. Or are there any restrictions that the json.hpp file from https://github.com/nlohmann/json/blob/develop/include/nlohmann/json.hpp of the repository was added in 2019 and has not been updated?

**Comment by abedra** [comment]
What is your goal with this issue? Is there a problem with the currently embedded version?
