### ISSUE TITLE
License information is completely missing

### ISSUE THREAD

**Issue by vuvova** [abedra/libvault#17]
There is no LICENSE file, there's no license comments in any of the source files, I was not able to find any hints to the license at all.

As far as I understand it is illegal to use a code that doesn't have the license and a copyright owner can sue over any such usage.

Could you please add a COPYING or LICENSE or anything?

**Comment by vuvova** [comment]
and if you haven't decided yet, may I suggest to use a GPLv2 compatible license, please?

**Comment by abedra** [comment]
Thanks for pointing this out, it was on oversight on the release and was not intentional. The MIT license is now in place for this project. Do you need a new release cut with this in place or do you use it as a submodule/copy?

**Comment by vuvova** [comment]
Thanks! We haven't decided if we will use libvault yet. I thought you might want to have a license anyway :smiley:
