### ISSUE TITLE
problem with experimental/optional header while building with -std=c++11 option

### ISSUE THREAD

**Issue by kishorek-0507** [abedra/libvault#24]
i am building this library using -std=c++11 flag but not able to find experimental/optional header file.
i have used the NONSTD_OPTIONAL_LITE_HPP to make it build..
but is it the right thing to do..
i have checked std::optional is available from c++17 onward.. 
how to solve this problem without using NONSTD_OPTIONAL_LITE_HPP

Thanks in Advance

**Comment by abedra** [comment]
The library has recently moved to C++17 and uses std::optional. All releases 0.2.0 or greater will have this.

**Comment by kishorek-0507** [comment]
Thanks for your prompt response...
Currently we don't have C++17.

[kkishore@rhel76 src]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


can you please let us know is there any way to build it with our current
configuration.

Thanks,
Kishore

**Comment by abedra** [comment]
The only way you will be able to build with your current configuration is if you install a newer compiler. The oldest supported version of GCC is 7, due to the C++17 requirement and use of std::optional. With the version of GCC posted, even previous versions of this library would not have worked due to the C++14 requirement and use of std::experimental::optional.

I recommend checking out https://developers.redhat.com/blog/2019/03/05/yum-install-gcc-8-clang-6/ for the instructions to update your compiler.

**Comment by kishorek-0507** [comment]
Hi Aaron,
We are using the older version (pre 0.2.0) and are able to perform Vault
login...vault kv PUT/GET operations using optional lite(
NONSTD_OPTIONAL_LITE_HPP) as workaround(as we can't upgrade our compiler).
now we need to support Vault LIST command..i don't see the support for this
in this older release..is there anyway to get vault list command work with
the current version of the library.
currently we are appending --request LIST after the Key name (at the end)
and using the Get API of the library as a work around..
can you please let us know anything we can do better.

Regards,
Kishore

**Comment by abedra** [comment]
If you are referring to the list function for key value, it is supported in the current version. A lot of cleanup, bug fixes, testing, and namespacing has been put in place since 0.2.0, so I recommend upgrading to the latest version to get support for key value list.
