### ISSUE TITLE
Problem with KeyValue Secret

### ISSUE THREAD

**Issue by leodlsrt** [abedra/libvault#65]
Hi !
I have detected a bug when i want to Read, Create a key/value secret, 
Your library make a HTTP request in GET to **/v1/mountPoint/data/mysecretname** 
but the good request is **/v1/mountPoint/mysecretname**.

Can you remove the "data" attribute in the URL to resolve that problem please ? 

Thanks,
Léo

https://www.vaultproject.io/api-docs/secret/kv/kv-v1

![image](https://user-images.githubusercontent.com/50668162/101491056-8e7c7a00-3963-11eb-8469-aaa13c2a0e3e.png)

**Comment by abedra** [comment]
Hi @leodlsrt. It sounds like you are using KV version 1 in your vault instance. Is that true? If so, you will need to specify version 1 when you construct your instance of `Vault::KeyValue`. An example can be found in the integration tests at https://github.com/abedra/libvault/blob/master/test/integration/engines/KeyValueTests.cpp#L9-L11.

If you are not using KV version 1 secrets, can you please provide more information?

**Comment by leodlsrt** [comment]
Thank you for your prompt response,
Yes, it's KV1 secret, it works if I specify in parameter the version. 
If I don't set the version as a parameter, it takes kv2, my bad.  

You can close this issue sorry and thanks for help!
