### ISSUE TITLE
Bad URL List() - AuthMethods

### ISSUE THREAD

**Issue by leodlsrt** [abedra/libvault#67]
Hi Aaron,
I've try 
When I try to use the list() function which concerns the Sys::Auth class, it returns a 404.
The correct url is: **http://localhost:8200/v1/sys/auth** and not **http://localhost:8200/v1/sys/auth/**

There is just one **/** too many that interferes with proper operation.

Thank you in advance for the correction,
Yours sincerely,
Leo
![image](https://user-images.githubusercontent.com/50668162/102758357-eeffb400-4372-11eb-8ac7-fdf450dd3781.png)

**Comment by leodlsrt** [comment]
When I trying manually with the / : 
![image](https://user-images.githubusercontent.com/50668162/102759000-d0e68380-4373-11eb-8fce-e1b4a2da4075.png)

Without the / :
![image](https://user-images.githubusercontent.com/50668162/102759644-ab0dae80-4374-11eb-927d-05b3514ce7b6.png)

**Comment by abedra** [comment]
Thanks for the report @leodlsrt. I'll get this fixed up and cut a release.

**Comment by abedra** [comment]
This has been resolved in release 0.32.0
