### ISSUE TITLE
Problem to Enable a Secret Engine

### ISSUE THREAD

**Issue by leodlsrt** [abedra/libvault#73]
Hi Aaron,
Thanks for the quick fix of the issue #71 , however, I see the same problem to enable a Secret Engine (mounts), when I try to do like this, the code doesn't execute it doesn't make any request to the server, it runs in a loop...

I think I should just add an optional parameter for the options on this line :
https://github.com/abedra/libvault/blob/a84359152c8e83d26e90f1d919572677e59b614f/include/VaultClient.h#L645

If needed, here is my code :
![image](https://user-images.githubusercontent.com/50668162/104162267-91500c00-53f4-11eb-88a2-080b02135d02.png)

Thank you very much,
Yours sincerely,
leodlsrt

**Comment by abedra** [comment]
Thanks for reporting @leodlsrt, I'll take a look and get this resolved.

**Comment by abedra** [comment]
Fixed and released in https://github.com/abedra/libvault/releases/tag/0.37.0
