### ISSUE TITLE
fatal error: catch2/catch.hpp: No such file or directory

### ISSUE THREAD

**Issue by VinayIsHere** [abedra/libvault#74]
When I run ```make``` I got the following error 
```
[ 98%] Building CXX object CMakeFiles/libvault_test.dir/test/test.cpp.o
/home/vinay/Documents/VinayPersonal/Contraly/github/libvault/test/test.cpp:2:10: fatal error: catch2/catch.hpp: No such file or directory
    2 | #include <catch2/catch.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/libvault_test.dir/build.make:63: CMakeFiles/libvault_test.dir/test/test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:484: CMakeFiles/libvault_test.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by abedra** [comment]
Hi @VinayIsHere,

This means you are missing the Catch2 dependency, listed in the [README](https://github.com/abedra/libvault#dependencies). If you are looking to run the unit or integration test suites, you will need this dependency. If you are simply looking to compile the library without running tests, you can specify -DENABLE_TEST=OFF (Details found [here](https://github.com/abedra/libvault/blob/master/CMakeLists.txt#L132)

**Comment by abedra** [comment]
You've likely installed from master. If you take a look at https://github.com/abedra/libvault/blob/master/.github/workflows/cmake.yml#L28-L35 you will see the appropriate version to install. Until the new version of Catch2 is released as stable libvault will use this branch.
