### ISSUE TITLE
Replace CMAKE_SOURCE_DIR with PROJECT_SOURCE_DIR in CMakeLists

### ISSUE THREAD

**Issue by valikund** [abedra/libvault#76]
Hi,

I am building a library on top of vault lib.
We are thinking about adding it through gitsbmodule or FetchContent.
Unfortunately, it does not work right now because of this funny cmake behaviour related to CMAKE_SOURCE_DIR.
https://stackoverflow.com/questions/22214349/modify-cmake-source-dir

Would you mind changing CMAKE_SOURCE_DIR to PROJECT_SOURCE_DIR?

I can create a pull request if you want, it is running locally.

**Comment by abedra** [comment]
All set, it's on master and the 0.38.0 release. What type of library are you building on top of libvault?

**Comment by valikund** [comment]
an opinionated client lib.
Thank you for your quick reaction!

**Comment by abedra** [comment]
Will you open source the library?

**Comment by valikund** [comment]
it will be closed source
